name: Minikube CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup-minikube:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies for Minikube
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          curl -LO https://storage.googleapis.com/minikube/releases/v1.29.0/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      # Start Minikube and set up kubectl
      - name: Start Minikube
        run: |
          minikube start --driver=docker  # Use Docker as the driver in CI
          minikube kubectl -- get nodes

      # Set up kubectl for later steps
      - name: Set up kubectl
        run: |
          echo "export KUBEVIRT_VERSION=latest" >> $GITHUB_ENV
          minikube kubectl -- get pods

    
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/my-app

      # Additional steps for testing or verification
      - name: Run Integration Tests
        run: |
          kubectl apply -f k8s/test-deployment.yaml
          kubectl wait --for=condition=available --timeout=60s deployment/test
          kubectl logs deployment/test
